name: publish

trigger:
  branches:
    exclude:
    - '*'
  tags:
    include: ["v*"]
pr: none

pool:
  vmImage: "ubuntu-22.04"

jobs:
- job: test
  displayName: Test
  strategy:
    matrix:
      Python38:
        python.version: '3.8'
      Python39:
        python.version: '3.9'
      Python310:
        python.version: '3.10'
      Python311:
        python.version: '3.11'
      Python312:
        python.version: '3.12'
  steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python $(python.version)'
    inputs:
      versionSpec: '$(python.version)'

  - script: |
      set -x

      python -m pip install -U tox
      python -m tox -e py

- job: build_and_deploy
  dependsOn: test
  displayName: Build and Deploy
  variables:
  - group: deployment-information

  steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python 3.9'
    inputs:
      versionSpec: '3.9'

  - script: |
      set -x
      python -m pip install -U build
      python -m build
      ls dist
    displayName: Build (Full)

  - script: |
      set -x
      cd model_setup
      python -m build --outdir ../dist
      ls ../dist
    displayName: Build (Model Only)

  - script: |
      set -xv  # Echo commands before they are run
      sudo env "PATH=$PATH" python -m pip install --no-cache-dir twine
      ls dist
      twine upload --skip-existing dist/*
    displayName: Deploy to PyPI
    env:
      TWINE_USERNAME: $(twineUsername)
      TWINE_PASSWORD: $(twinePassword)
