name: tests

trigger: ["*"]
pr: ["*"]

pool:
  vmImage: "ubuntu-20.04"

resources:
  containers:
  - container: "3.8"
    image: python:3.8
  - container: "3.9"
    image: python:3.9
  - container: "3.10"
    image: python:3.10
  - container: "3.11"
    image: python:3.11

jobs:
  - job: run_test
    strategy:
      matrix:
        Python3_8:
          python.version: "3.8"
        Python3_9:
          python.version: "3.9"
        Python3_10:
          python.version: "3.10"
        Python3_11:
          python.version: "3.11"

    timeoutInMinutes: 10

    container: $[ variables['python.version'] ]

    steps:
      - script: |
          # Install poetry and add executable to PATH
          curl -sSL https://install.python-poetry.org | python3 -
          export PATH="/root/.local/bin:$PATH"

          [ ! -d "$(pwd)/tests" ] && echo "No tests found" && exit
          [ -f $(pwd)/requirements.txt ] && env "PATH=$PATH" python -m pip install -U --no-cache-dir -r $(pwd)/requirements.txt
          [ -f $(pwd)/tests/requirements.txt ] && env "PATH=$PATH" python -m pip install -U --no-cache-dir -r $(pwd)/tests/requirements.txt

        displayName: Setup environment
      - script: |
          [ ! -d "$(pwd)/tests" ] && echo "No tests found" && exit
          export REPO_NAME=${BUILD_REPOSITORY_NAME##*/}
          python -m pytest -p no:cacheprovider --durations=10 -rsx -vv -W ignore::DeprecationWarning
        displayName: Test
